### ISSUE TITLE
Filter Based On Current KPI Status

### ISSUE THREAD

**Issue by hiremadhan** [microsoft/PowerBI-visuals-PowerKPIMatrix#10]
@EugeneElkin and @ignatvilesov

Is it possible to filter on Latest KPI Status .. Like I want to Filter the Visual with Latest KPI Status is Negative , but it should not Filter for All the Year which means the Trend should be the same( it shouldnt remove where KPI Status is POsitive Previous Day or any other day in that Year)

![image](https://user-images.githubusercontent.com/52971891/62839204-767be400-bca4-11e9-8af4-552de0de7992.png)

Can you please help where to add this filter in this code.

**Comment by EugeneElkin** [comment]
Hello,

I am afraid that it is impossible because filers are applied to a whole data set.
At least, I haven't found how to do it.
However, you should try to use DAX to select necessary data.

Kind Regards,
Evgenii Elkin
